#g++ hello.cpp -I/usr/local/include/node -L/home/wyy/Code/node/out/Release -lv8 -lv8_base -lv8_nosnapshot -luv -lpthread -o hello
hello:
	g++ hello.cpp -I/usr/local/include/node -L/home/wyy/Code/node/out/Release -lv8 -lpthread -o hello
clean:
	rm hello
