// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "tests.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  std;

class testsHandler : virtual public testsIf {
 public:
  testsHandler() {
    // Your initialization goes here
  }

  void test1(std::string& _return, const std::string& doc_id) {
    // Your implementation goes here
    printf("test1\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<testsHandler> handler(new testsHandler());
  shared_ptr<TProcessor> processor(new testsProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

