/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tests_CONSTANTS_H
#define tests_CONSTANTS_H

#include "tests_types.h"



class testsConstants {
 public:
  testsConstants();

};

extern const testsConstants g_tests_constants;



#endif
