/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef insight_CONSTANTS_H
#define insight_CONSTANTS_H

#include "insight_types.h"



class insightConstants {
 public:
  insightConstants();

};

extern const insightConstants g_insight_constants;



#endif
