// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Insight.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ;

class InsightHandler : virtual public InsightIf {
 public:
  InsightHandler() {
    // Your initialization goes here
  }

  void Hello(Person& _return, const Person& person) {
    // Your implementation goes here
    printf("Hello\n");
  }

  void Hi(Person& _return, const Person& p1, const Person& p2) {
    // Your implementation goes here
    printf("Hi\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<InsightHandler> handler(new InsightHandler());
  shared_ptr<TProcessor> processor(new InsightProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

