all:
	g++ -o client client.cpp
	gcc -o raw_socket raw_socket.c
	gcc -o raw_socket2 raw_socket2.c
raw_socket:
	gcc -o raw_socket raw_socket.c
raw_socket2:
	gcc -o raw_socket2 raw_socket2.c
clean:
	rm -rf raw_socket raw_socket2 client
